language: go

os:
  - linux
  - osx

go:
  - 1.12

script:
  - go test -v ./...
  - CGO_ENABLED=0 go build -a -o build/catenv_$TRAVIS_OS_NAME -ldflags "-s -w -extldflags -static" cmd/catenv/catenv.go

deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file:
    - build/catenv_$TRAVIS_OS_NAME
  skip_cleanup: true
  on:
    tags: true